spring:
  datasource:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jwt:
    secret: 'comet2059!'
server:
  port: 8080
logging:
  file:
    name: log/toolbox.log
    max-size: 10MB
    max-history: 1000
